### ISSUE TITLE
Followed everything on install instructions, but still not working [Linux]

### ISSUE THREAD

**Issue by ghost** [TerrariaPrismTeam/Prism#20]
As the title says, I followed the install instructions and when I click run, nothing happens.
![screenshot from 2016-01-17 20 10 17](https://cloud.githubusercontent.com/assets/13139069/12379243/6e3e76c8-bd56-11e5-94dd-9cf59be24687.png)
And, when I click run in terminal, this happens.
![screenshot from 2016-01-17 20 10 25](https://cloud.githubusercontent.com/assets/13139069/12379244/6e3f3a9a-bd56-11e5-98bc-5ab920546d5c.png)
Help?

**Comment by PoroCYon** [comment]
As you can see on [Line 11](https://github.com/TerrariaPrismTeam/Prism/blob/develop/Prism.sh#L11), it depends on the current directory.
Open a terminal, `cd` to the directory and run `./Prism.sh` (you might have to allow it to run first, though).
